import type {BuilderDocument,ProcedureSection} from '../model';
import {procedureTemplateLogo} from './procedure-logo';
import {escapeHtml,rich,safeUrl} from '../rich-text';
// Visual tokens and grouping distilled from Procedure Template (3).docx.
export const procedureTheme={magenta:'#982371',teal:'#8FD4D5',orange:'#FFA412',gray:'#D9D9D9',ink:'#000000',font:'Arial,Helvetica,sans-serif'};
export const knowledgePanels=[
 {key:'when_to_use',title:'When to use',fields:[['when_to_use',''],['general_knowledge','General knowledge'],['related_concepts','Related concepts']]},
 {key:'guidelines',title:'Guidelines, Regulations & Exceptions',fields:[['guidelines_rules','Guidelines / Rules'],['regulations','Regulations'],['service_accuracy_expectations','Service / Accuracy Expectations'],['exceptions','Exceptions']]},
 {key:'risks',title:'Risks & Key Controls',fields:[['risks','Risks'],['controls','Controls'],['required_actions','Required actions'],['audit_critical_information','Audit-critical information'],['warnings','Warnings']]},
 {key:'tools',title:'Tools & Resources',fields:[['systems_applications','Systems / Applications'],['forms_documents','Forms / Documents'],['links_references','Links / References'],['reports','Reports'],['contacts_resources','Contacts / Resources']]},
 {key:'other',title:'Other',fields:[['definitions_key_terms','Definitions / Key Terms'],['roles_responsibilities','Roles & Responsibilities'],['triggers','Triggers'],['inputs_prerequisites','Inputs / Prerequisites'],['outputs_results','Outputs / Results']]}
] as const;
const e=escapeHtml;
const styledRich=(v:string)=>rich(v).replace(/<p>/g,'<p style="margin:4px 0;line-height:1.5">').replace(/<ul>/g,'<ul style="margin:6px 0;padding-left:26px;list-style-type:disc">').replace(/<ol>/g,'<ol style="margin:6px 0;padding-left:26px;list-style-type:decimal">').replace(/color:#315d4c/g,'color:#0000EE');
const inlineRich=(v:string)=>styledRich(v).replace(/^<p[^>]*>/,'').replace(/<\/p>$/,'');
const bullets=(items:string[])=>items.filter(x=>x.trim()).length?`<ul style="margin:7px 0;padding-left:28px;list-style-type:disc">${items.filter(x=>x.trim()).map(x=>`<li style="padding:2px 0">${styledRich(x)}</li>`).join('')}</ul>`:'';
const bar=(title:string,id:string,secondary=false)=>`<h${secondary?'3':'2'} id="${id}" style="font-family:${procedureTheme.font};font-size:16px;line-height:1.4;font-weight:700;letter-spacing:${secondary?'0':'0.6px'};color:${secondary?'#000000':'#FFFFFF'};background-color:${secondary?procedureTheme.teal:procedureTheme.magenta};padding:${secondary?'3px 6px':'4px 6px'};margin:22px 0 10px">${e(title)}</h${secondary?'3':'2'}>`;
const sub=(title:string,body:string)=>body?`<section style="margin:14px 0"><h4 style="font-size:14px;font-weight:700;text-decoration:underline;color:#000;margin:10px 0 6px">${e(title)}</h4>${body}</section>`:'';
function knowledge(d:BuilderDocument){return knowledgePanels.map(panel=>{const body=panel.fields.map(([key,label])=>{const items=d.fields[key]||[];if(!items.some(x=>x.trim()))return '';return `${label?`<p style="font-weight:700;margin:10px 0 4px">${e(label)}</p>`:''}${bullets(items)}`;}).join('');const categories=(d.knowledgeSubcategories?.[panel.key]||[]).filter(x=>x.title.trim()||x.content.trim());if(!body&&!categories.length)return '';return `<table aria-label="${e(panel.title)}" style="width:100%;border-collapse:collapse;border:1px solid #000;margin:12px 0 20px;table-layout:fixed"><thead><tr><th scope="col" style="text-align:left;font-size:16px;font-weight:700;background-color:${procedureTheme.teal};color:#000;border:1px solid #000;padding:8px">${e(panel.title)}</th></tr></thead><tbody>${body?`<tr><td style="border:1px solid #000;padding:8px 12px;overflow-wrap:anywhere">${body}</td></tr>`:''}${categories.map(x=>`<tr><td style="border:1px solid #000;padding:8px 12px;overflow-wrap:anywhere"><h4 style="font-size:14px;font-weight:700;margin:0 0 8px;padding:3px 6px;background-color:${procedureTheme.orange};color:#000;border:1px solid #000">${e(x.title)}</h4>${styledRich(x.content)}</td></tr>`).join('')}</tbody></table>`;}).join('');}
function section(p:ProcedureSection,index:string,level=0):string{const cell='border:1px solid #000;padding:6px 8px;text-align:left;vertical-align:top;overflow-wrap:anywhere';const sequence=p.steps.map(s=>{if(s.callout)return `<aside style="background-color:${procedureTheme.gray};color:#000;padding:5px 8px;margin:14px 0;line-height:1.5"><strong style="color:#FF0000">${s.callout==='warning'?'Warning!':'Important!'}</strong> ${inlineRich(s.instruction)}</aside>`;return `<li style="padding:2px 0 2px 2px">${styledRich(s.instruction)}${s.image&&safeUrl(s.image,true)?`<figure style="margin:10px 0"><img src="${e(s.image)}" alt="${e(s.description)}" style="max-width:100%;height:auto">${s.description?`<figcaption style="font-size:12px;color:#555">${e(s.description)}</figcaption>`:''}</figure>`:''}${s.substeps?.length?`<ol style="list-style-type:lower-alpha;margin:6px 0;padding-left:24px">${s.substeps.map(substep=>`<li style="padding:2px 0">${styledRich(substep.instruction)}</li>`).join('')}</ol>`:''}</li>`;}).join('');const ordered=`<ol style="margin:10px 0 18px;padding-left:29px;list-style-type:decimal">${sequence}</ol>`;return `<section>${bar(p.title||'Untitled section',`procedure-${index}`,level>0)}${styledRich(p.purpose)}${sub('Prerequisites',bullets(p.prerequisites))}${ordered}${p.notes.filter(x=>x.trim()).map(x=>`<aside style="background-color:${procedureTheme.gray};color:#000;padding:4px 8px;margin:14px 0 14px 24px;line-height:1.5"><strong style="color:#FF0000">Important!</strong> ${inlineRich(x)}</aside>`).join('')}${p.decisions.length?`<table aria-label="Decision logic for ${e(p.title)}" style="width:100%;table-layout:fixed;border-collapse:collapse;margin:18px 0"><thead><tr><th scope="col" style="${cell};background-color:${procedureTheme.gray};width:25%;font-weight:700">If</th><th scope="col" style="${cell};background-color:${procedureTheme.gray};font-weight:700">Then</th></tr></thead><tbody>${p.decisions.map(x=>x.original?`<tr><td colspan="2" style="${cell}"><strong>Original decision:</strong> ${styledRich(x.original)}</td></tr>`:`<tr><td style="${cell}">${styledRich(x.condition)}</td><td style="${cell}">${styledRich(x.result)}</td></tr>`).join('')}</tbody></table>`:''}${sub('Exceptions',bullets(p.exceptions))}${p.warnings.filter(x=>x.trim()).map(x=>`<aside style="background-color:${procedureTheme.gray};color:#000;padding:5px 8px;margin:12px 0 12px 24px"><strong style="color:#FF0000">Warning!</strong> ${inlineRich(x)}</aside>`).join('')}${sub('Expected result',styledRich(p.expectedResult))}${sub('Sources',bullets(p.sources))}${(p.subsections||[]).map((child,i)=>section(child,`${index}-${i+1}`,level+1)).join('')}</section>`;}
export function renderProcedureHtml(d:BuilderDocument){const effectiveDate=d.owner||d.effectiveDate;const formattedEffectiveDate=/^\d{4}-\d{2}-\d{2}$/.test(effectiveDate)?new Date(`${effectiveDate}T12:00:00`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):effectiveDate;const basic=knowledge(d);const resources=bullets(d.fields.supporting_resources||[]);const contacts=bullets(d.fields.contacts||[]);const revisions=[...(formattedEffectiveDate?[`Effective date: ${formattedEffectiveDate}`]:[]),...(d.fields.revision_history||[]).map(x=>`Revision history: ${x}`),...(d.fields.last_reviewed||[]).map(x=>`Last reviewed: ${x}`),...(d.fields.initial_release||[]).map(x=>`Initial Release: ${x}`),...(d.fields.revision_information||[])];const supporting=resources||contacts||revisions.length;const toc=[...(basic?[{id:'basic-knowledge',title:'Basic Knowledge'}]:[]),...d.procedures.map((p,i)=>({id:`procedure-${i+1}`,title:p.title||`Section ${i+1}`})),...(supporting?[{id:'supporting-resources',title:'Supporting Resources'}]:[])];return `<article aria-label="Procedure document" style="font-family:${procedureTheme.font};font-size:14px;line-height:1.5;color:#000000;max-width:900px;margin:0 auto;overflow-wrap:anywhere"><header style="border-bottom:1px solid #333;padding:0 0 20px;margin:0 0 26px;min-height:58px"><img src="${procedureTemplateLogo}" width="86" height="32" alt="STCU" style="float:left;max-width:20%;height:auto;margin:2px 16px 8px 0"><h1 style="font-family:${procedureTheme.font};font-size:20px;font-weight:700;letter-spacing:0.5px;text-align:right;color:#000;margin:0 0 3px;line-height:1.3">${e(d.title||'Procedure title')}</h1><p style="font-size:13px;text-align:right;color:#000;margin:0">${e([d.audience,'Procedure',formattedEffectiveDate?`Effective ${formattedEffectiveDate}`:''].filter(Boolean).join(' | '))}</p><div style="clear:both"></div></header>${bar('Purpose','purpose')}${styledRich(d.purpose)}${toc.length?`${bar('Sections (TOC)','contents')}<p style="margin:8px 0">This procedure contains ${toc.length} sections.</p><ul style="padding-left:28px;margin:12px 0 24px;list-style-type:disc">${toc.map(x=>`<li style="padding:2px 0"><a href="#${x.id}" style="color:#0000EE;text-decoration:underline">${e(x.title)}</a></li>`).join('')}</ul>`:''}${basic?bar('Basic Knowledge','basic-knowledge')+basic:''}${d.procedures.map((p,i)=>section(p,String(i+1))).join('')}${supporting?`${bar('Supporting Resources','supporting-resources')}${resources}${contacts?bar('Contact(s)','contacts',true)+contacts:''}${revisions.length?bar('Revision Information','revision-information',true)+bullets(revisions):''}`:''}</article>`;}
