import type {BuilderDocument,Entry} from '../model';
import {escapeHtml,rich,safeUrl} from '../rich-text';
import {formatContact} from '../contacts';
import {procedureTemplateLogo} from './procedure-logo';

const magenta='#982371',gray='#A6A6A6';
const formatDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(`${value}T12:00:00`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):value;
const header=(d:BuilderDocument,label:string)=>{const audience=d.type==='how-to'?d.audience||'Audience':d.audience||'Department';const effectiveDate=formatDate(d.effectiveDate||d.owner||d.fields.effective_date?.[0]||'Effective Date');const initialRelease=d.type==='how-to'?formatDate(d.fields.initial_release?.[0]||''):'';const title=d.type==='how-to'?`How To: ${d.title||'[Action or Problem]'}`:d.title||'Insert title';return `<header style="border-bottom:1px solid ${gray};padding:0 0 8px;margin-bottom:26px;min-height:52px"><img src="${procedureTemplateLogo}" width="86" height="32" alt="STCU" style="float:left;height:auto;margin:2px 16px 8px 0"><h1 style="font:700 20px Arial,Helvetica,sans-serif;text-align:right;margin:0;color:#000">${escapeHtml(title)}</h1><p style="font:13px Arial,Helvetica,sans-serif;text-align:right;margin:3px 0;color:#000">${escapeHtml([audience,label,effectiveDate,initialRelease?`Initial release ${initialRelease}`:''].filter(Boolean).join(' | '))}</p><div style="clear:both"></div></header>`;};
const bar=(title:string)=>`<h2 style="background:${magenta};color:#fff;font:700 17px Arial,Helvetica,sans-serif;padding:4px 8px;margin:23px 0 8px">${escapeHtml(title)}</h2>`;
const purpose=(d:BuilderDocument)=>`<section><h2 style="font:700 16px Arial,Helvetica,sans-serif;margin:0 0 3px">Purpose</h2>${rich(d.purpose)}</section>`;
const entries=(d:BuilderDocument)=>d.entries.filter(e=>e.title.trim()||e.content.trim());
const helpItems=(d:BuilderDocument)=>{const extension=d.fields.extension?.[0]||'';const ticket=d.fields.ticket_link?.[0]||d.fields.submit_a_ticket?.[0]||'';const related=d.fields.related_procedures?.length?d.fields.related_procedures:d.fields.link_to_procedure||[];const ticketText=safeUrl(ticket)?`<a href="${escapeHtml(ticket)}" style="color:#315d4c">${escapeHtml(ticket)}</a>`:escapeHtml(ticket);const contact=d.owner?`<li><strong>Contact:</strong> ${escapeHtml(d.owner)}${extension?` · Ext. ${escapeHtml(extension)}`:''}</li>`:'';return [contact,ticket?`<li><strong>Submit a ticket:</strong> ${ticketText}</li>`:'',...related.filter(Boolean).map(value=>`<li><strong>Related procedure:</strong> ${rich(value)}</li>`)].filter(Boolean).join('');};
const support=(d:BuilderDocument)=>{const more=d.fields.need_more_details||d.fields.supporting_resources||[];const legacy=d.fields.need_help||(d.fields.contacts||[]).map(formatContact);const help=[...legacy.map(value=>`<li>${rich(value)}</li>`),helpItems(d)].filter(Boolean).join('');return `${more.length?`<section style="border-top:2px solid ${gray};padding-top:16px;margin-top:20px"><h3 style="margin:0;font:700 16px Arial,Helvetica,sans-serif">Need more details?</h3><ul>${more.map(x=>`<li>${rich(x)}</li>`).join('')}</ul></section>`:''}${help?`<section style="border-top:2px solid ${gray};padding-top:16px;margin-top:20px"><h3 style="margin:0;font:700 16px Arial,Helvetica,sans-serif">Need Help</h3><ul>${help}</ul></section>`:''}`;};
const row=(e:Entry)=>`<tr><td style="padding:12px;border:1px solid #333;vertical-align:top">${rich(e.title)}</td><td style="padding:12px;border:1px solid #333;vertical-align:top">${rich(e.content)}</td></tr>`;
const substeps=(items:{instruction:string}[])=>items.length?`<ol style="list-style-type:lower-alpha;margin:6px 0 0 20px;padding-left:18px">${items.map(item=>`<li>${rich(item.instruction)}</li>`).join('')}</ol>`:'';
const jobAid=(d:BuilderDocument,two=false)=>{const reminders=d.fields.key_reminders||[];const cards=entries(d).map((e,i)=>two?`${bar(e.title||`Section ${i+1}`)}<table style="width:100%;border-collapse:collapse"><thead><tr><th style="width:50%;background:#FFA412;border:1px solid #333;padding:4px">Action</th><th style="width:50%;background:#FFA412;border:1px solid #333;padding:4px">Action</th></tr></thead><tbody><tr><td style="padding:12px;border:1px solid #333;vertical-align:top">${rich(e.content.split('\n').slice(0,Math.ceil(e.content.split('\n').length/2)).join('\n'))}</td><td style="padding:12px;border:1px solid #333;vertical-align:top">${rich(e.content.split('\n').slice(Math.ceil(e.content.split('\n').length/2)).join('\n'))}</td></tr></tbody></table>`:`${bar(e.title||`Section ${i+1}`)}<table style="width:100%;border-collapse:collapse"><thead><tr><th style="background:#D9D9D9;border:1px solid #333;padding:4px;text-align:left">Step | Action</th></tr></thead><tbody><tr><td style="padding:12px;border:1px solid #333;vertical-align:top">${rich(e.content)}</td></tr></tbody></table>`).join('');return (reminders.length?`<section style="border-top:2px solid ${gray};margin-top:14px;padding-top:12px"><h3 style="margin:0;font:700 16px Arial,Helvetica,sans-serif">Key Reminders <i style="font-weight:400">(optional)</i></h3>${reminders.map(rich).join('')}</section>`:'')+cards+support(d);};
const howTo=(d:BuilderDocument)=>{const items=(key:string)=>d.fields[key]||[];const bullets=(values:string[])=>values.length?`<ul>${values.map(value=>`<li>${rich(value)}</li>`).join('')}</ul>`:'';const labelled=(label:string,key:string)=>items(key).map(value=>`<li><strong>${label}</strong> ${rich(value)}</li>`).join('');const purposeBlock=`<section>${rich(d.purpose)}</section>`;const beforeItems=[...items('before_you_start'),...items('required_access'),...items('required_apps_setup'),...items('pre_steps')];const before=beforeItems.length?`<section style="border-top:2px solid ${gray};margin-top:14px;padding:12px 0"><h2 style="font:700 16px Arial,Helvetica,sans-serif;margin:0">Before You Start</h2>${bullets(beforeItems)}</section>`:'';let stepNumber=0;const steps=d.procedures.map(p=>{if(p.callout)return `<aside style="background-color:#D9D9D9;color:#000;padding:5px 8px;margin:14px 0;line-height:1.5"><strong style="color:#FF0000">${p.callout==='warning'?'Warning!':'Important!'}</strong> ${rich(p.purpose).replace(/^<p>/,'').replace(/<\/p>$/,'')}</aside>`;stepNumber+=1;const instruction=p.purpose.trim()?p.purpose:p.steps.map(step=>step.instruction).filter(Boolean).join('\n');return `<section><h3 style="font:700 16px Arial,Helvetica,sans-serif;margin:14px 0 4px">Step ${stepNumber}: ${escapeHtml(p.title||'Action')}</h3>${rich(instruction)}</section>`;}).join('');const issues=items('if_issue'),actions=items('do_this');const troubleshooting=issues.length||actions.length?`<section style="border-top:2px solid ${gray};margin-top:18px;padding:12px 0"><h2 style="font:700 16px Arial,Helvetica,sans-serif;margin:0">If Something Doesn’t Work</h2>${Array.from({length:Math.max(issues.length,actions.length)},(_,index)=>{const issue=escapeHtml(issues[index]||'another issue');const action=actions[index]?rich(actions[index]).replace(/^<p>/,'').replace(/<\/p>$/,''):'';return `<div style="margin:10px 0"><p style="margin:0 0 4px"><strong>If ${issue}:</strong></p>${action?`<ul style="margin:0;padding-left:28px"><li>${action}</li></ul>`:''}</div>`;}).join('')}</section>`:'';const notes=items('important_notes');const help=helpItems(d);return `${purposeBlock}${before}${bar('Steps to Complete')}${steps}${troubleshooting}${notes.length?`<section style="border-top:2px solid ${gray};margin-top:18px;padding:12px 0"><h2 style="font:700 16px Arial,Helvetica,sans-serif;margin:0">Important Notes</h2>${bullets(notes)}</section>`:''}${help?`${bar('Need Help?')}<ul>${help}</ul>`:''}`;};
export function renderStcuTemplate(d:BuilderDocument){let body='';if(d.type==='faq'){body=bar('Frequently Asked Questions (FAQ)')+entries(d).map(e=>`<section style="padding:0 0 18px;margin:0 0 18px;border-bottom:2px solid ${gray}"><h3 style="font:700 16px Arial,Helvetica,sans-serif;margin:0 0 5px">${escapeHtml(e.title||'Question')}</h3>${rich(e.content)}</section>`).join('')+support(d);}else if(d.type==='decision-table'){body=`<table style="width:100%;border-collapse:collapse;margin-top:22px"><thead><tr><th style="width:64%;background:${magenta};color:#fff;border:1px solid #333;padding:8px;text-align:left">Scenario</th><th style="background:${magenta};color:#fff;border:1px solid #333;padding:8px;text-align:left">Solution</th></tr></thead><tbody>${entries(d).map(row).join('')}</tbody></table>`+support(d);}else if(d.type==='how-to')body=howTo(d);else if(d.type==='job-aid-one-column')body=jobAid(d);else if(d.type==='job-aid-two-column')body=jobAid(d,true);else body=entries(d).map((e,i)=>`${bar(e.title||`Section ${i+1}`)}<div style="border:1px solid #555;min-height:30px;padding:8px">${rich(e.content)}</div>`).join('')+support(d);const intro=d.type==='how-to'?'':purpose(d);return `<article aria-label="${escapeHtml(d.type)} document" style="font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.5;color:#000;max-width:900px;margin:0 auto">${header(d,d.type==='quick-reference'?'Quick Reference Guide':d.type==='faq'?'FAQ':d.type==='how-to'?'How To':d.type==='decision-table'?'Decision Table':'Job Aid')}${intro}${body}</article>`;}
