import {newDocument,newSection,newStep,uid,type BuilderDocument,type DocumentType} from './model';
import {types} from './config';
type Obj=Record<string,unknown>;
const obj=(v:unknown):Obj=>v&&typeof v==='object'&&!Array.isArray(v)?v as Obj:{};
const text=(v:unknown):string=>typeof v==='string'?v:typeof v==='number'?String(v):v==null?'':Array.isArray(v)?v.map(text).join('\n'):text(obj(v).content??obj(v).instruction??obj(v).text??obj(v).description??obj(v).name??obj(v).title??JSON.stringify(v));
const arr=(v:unknown):unknown[]=>v==null?[]:Array.isArray(v)?v:[v];
const strings=(v:unknown)=>arr(v).map(text);
const key=(v:string)=>v.replace(/\\_/g,'_').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/_$/,'');
function normalize(v:unknown):unknown{if(Array.isArray(v))return v.map(normalize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,val])=>[key(k),normalize(val)]));return v;}
function documentType(value:string):DocumentType{const normalized=key(value);const exact=Object.keys(types).find(type=>key(type)===normalized);if(exact)return exact as DocumentType;if(normalized.includes('how'))return 'how-to';if(normalized.includes('decision'))return 'decision-table';if(normalized.includes('quick'))return 'quick-reference';if(normalized.includes('job_aid')&&(normalized.includes('two')||normalized.includes('_2_')))return 'job-aid-two-column';if(normalized.includes('job_aid'))return 'job-aid-one-column';if(normalized.includes('reference'))return 'reference';if(normalized.includes('faq'))return 'faq';return 'procedure';}
export function importAgentJson(input:string):{document:BuilderDocument;summary:string}{let raw:unknown;try{raw=JSON.parse(input);}catch{raw=JSON.parse(input.replace(/\\_/g,'_'));}if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Import a JSON object containing document information and procedures.');const root=obj(normalize(raw));const info=obj(root.document);const requested=text(info.document_type??info.type??root.document_type);const type=documentType(requested);const d=newDocument(type);d.procedures=[];d.importOriginal=raw;const review:Obj={};
const take=(source:Obj,names:string[],path:string)=>{const name=names.find(n=>source[n]!==undefined);if(!name)return undefined;const value=source[name];delete source[name];if(typeof value==='object'&&value!==null)review[`${path}.${name} (original metadata)`]=value;return value;};
const metadata={...info};d.title=text(take(metadata,['title','document_title'],'document'));d.audience=text(take(metadata,['audience','target_audience'],'document'));d.purpose=text(take(metadata,['purpose','summary'],'document'));d.owner=text(take(metadata,['content_owner','owner'],'document'));d.effectiveDate=text(take(metadata,['effective_date'],'document'));delete metadata.document_type;delete metadata.type;if(Object.keys(metadata).length)review.document=metadata;
const remaining={...root};delete remaining.document;delete remaining.document_type;
d.title=d.title.replace(/[<>]/g,'');
const aliases:Record<string,string[]>={definitions_key_terms:['definitions','key_terms'],guidelines_rules:['guidelines','rules'],service_accuracy_expectations:['service_expectations','accuracy_expectations'],systems_applications:['systems','applications'],forms_documents:['forms','documents'],links_references:['links','references'],contacts_resources:['contacts','resources'],inputs_prerequisites:['inputs','prerequisites'],outputs_results:['outputs','results']};
for(const g of types[type].groups){const source={...obj(remaining[g.key])};for(const f of g.fields){const names=[f.key,...(aliases[f.key]||[])];let value=take(source,names,g.key);if(value===undefined)value=take(remaining,names,'root');if(value!==undefined)d.fields[f.key]=strings(value);}if(remaining[g.key]!==undefined){delete remaining[g.key];if(Object.keys(source).length)review[g.key]=source;}}
if(type==='procedure'){const mergeGroup=(target:string,groups:string[])=>{const values=groups.flatMap(groupName=>{const value=remaining[groupName];if(value===undefined)return [];delete remaining[groupName];const sourceValue=obj(value);return Object.keys(sourceValue).length?Object.values(sourceValue).flatMap(strings):strings(value);}).filter(Boolean);if(values.length)d.fields[target]=[...(d.fields[target]||[]),...values];};mergeGroup('when_to_use',['basic_knowledge']);mergeGroup('guidelines_regulations_exceptions',['guidelines_regulations_exceptions']);mergeGroup('risks_key_controls',['risks_controls']);mergeGroup('tools_resources',['tools_resources']);mergeGroup('other',['roles_responsibilities','triggers_inputs_outputs','other_information']);}
const procedures=arr(take(remaining,['procedures','procedure_sections'],'root'));procedures.forEach((value,index)=>{const psrc={...obj(value)};const p=newSection();const path=`procedures[${index}]`;p.title=text(take(psrc,['title','section_title','procedure_title','name'],path));p.purpose=text(take(psrc,['purpose'],path));p.prerequisites=strings(take(psrc,['prerequisites'],path));p.notes=strings(take(psrc,['important_information','notes'],path));p.warnings=strings(take(psrc,['warnings'],path));p.exceptions=strings(take(psrc,['exceptions'],path));p.expectedResult=text(take(psrc,['expected_result','expected_results'],path));p.sources=strings(take(psrc,['sources','source'],path));p.steps=arr(take(psrc,['steps'],path)).map(v=>{const s=obj(v);return {...newStep(),instruction:text(s.instruction??s.content??s.text??v),image:text(s.image??s.screenshot??''),description:text(s.visual_description??s.description??'')};});p.decisions=arr(take(psrc,['decision_logic','decisions'],path)).map(v=>{const x=obj(v);const condition=text(x.condition??x.if);const result=text(x.result??x.then);return {id:uid(),condition,result,original:condition&&result?'':text(x.content??v)};});p.subsections=arr(take(psrc,['subsections','sub_sections'],path)).map(child=>importAgentJson(JSON.stringify({document:{document_type:'procedure'},procedures:[child]})).document.procedures[0]);if(Object.keys(psrc).length)review[path]=psrc;d.procedures.push(p);});
if(!['procedure','how-to'].includes(type)){const entryNames=type==='faq'?['faqs','questions','entries']:type==='decision-table'?['decision_table','decisions','scenarios','rows','entries']:type==='quick-reference'?['sections','content_sections','quick_reference','entries']:type.startsWith('job-aid')?['job_aid','job_aid_items','items','entries','steps']:['sections','content_sections','entries'];d.entries=arr(take(remaining,entryNames,'root')).map(v=>{const e=obj(v);return {id:uid(),title:text(e.question??e.scenario??e.title??e.name),content:text(e.answer??e.solution??e.content??e.action??e.instruction??v)};});}
Object.assign(review,remaining);d.unmapped=Object.keys(review).length?review:null;return {document:d,summary:`Imported ${d.procedures.length} procedure sections and ${d.procedures.reduce((n,p)=>n+p.steps.length,0)} steps. ${d.unmapped?'Original values and unmatched content are retained for review.':'All recognized fields mapped.'}`};}
