export type DocumentType = 'procedure' | 'how-to' | 'faq' | 'reference' | 'decision-table' | 'job-aid-one-column' | 'job-aid-two-column' | 'quick-reference';
export type Substep = {id:string; instruction:string};
export type Step = {id:string; instruction:string; image:string; description:string; substeps:Substep[]};
export type Decision = {id:string; condition:string; result:string; original:string};
export type ProcedureSection = {id:string; title:string; purpose:string; prerequisites:string[]; steps:Step[]; decisions:Decision[]; notes:string[]; exceptions:string[]; warnings:string[]; expectedResult:string; sources:string[]; subsections?:ProcedureSection[]; template?:'how-to'};
export type Entry = {id:string; title:string; content:string};
export const currentSchemaVersion = 2;
export type BuilderDocument = {schemaVersion:number; id:string; type:DocumentType; title:string; audience:string; purpose:string; owner:string; effectiveDate:string; modified:string; fields:Record<string,string[]>; procedures:ProcedureSection[]; entries:Entry[]; unmapped:unknown; knowledgeSubcategories?:Record<string,Entry[]>; importOriginal?:unknown};
export const uid=()=>globalThis.crypto?.randomUUID?.() || Math.random().toString(36).slice(2);
export const newStep=():Step=>({id:uid(),instruction:'',image:'',description:'',substeps:[]});
export const newSection=():ProcedureSection=>({id:uid(),title:'',purpose:'',prerequisites:[],steps:[newStep()],decisions:[],notes:[],exceptions:[],warnings:[],expectedResult:'',sources:[]});
export function newDocument(type:DocumentType='procedure'):BuilderDocument{const firstSection=newSection();if(type==='how-to')firstSection.template='how-to';return {schemaVersion:currentSchemaVersion,id:uid(),type,title:'',audience:'',purpose:'',owner:'',effectiveDate:'',modified:new Date().toISOString(),fields:{},procedures:type==='procedure'||type==='how-to'?[firstSection]:[],entries:[],unmapped:null};}
export function validate(d:BuilderDocument){const errors:string[]=[];if(!d.title.trim())errors.push('Add a document title.');if(!d.purpose.trim())errors.push(d.type==='faq'?'Add a summary.':'Add a purpose.');if(['procedure','how-to'].includes(d.type)){if(!d.procedures.length)errors.push('Add at least one procedure section.');const checkSection=(p:ProcedureSection,path:string)=>{if(!p.title.trim())errors.push(`${path}: add a title.`);if(d.type==='how-to'){if(!p.purpose.trim()&&!p.steps.some(step=>step.instruction.trim()))errors.push(`${path}: add a short, direct instruction.`);return;}if(!p.steps.length)errors.push(`${path}: add at least one step.`);p.steps.forEach((s,j)=>{if(!s.instruction.trim())errors.push(`${path}, step ${j+1}: add an instruction.`);});p.decisions.forEach((x,j)=>{if(!x.original.trim()&&(!x.condition.trim()||!x.result.trim()))errors.push(`${path}, decision ${j+1}: complete IF and THEN.`);});(p.subsections||[]).forEach((sub,i)=>checkSection(sub,`${path}, subsection ${i+1}`));};d.procedures.forEach((p,i)=>checkSection(p,`Section ${i+1}`));}if(['faq','reference','decision-table','job-aid-one-column','job-aid-two-column','quick-reference'].includes(d.type)){if(!d.entries.length)errors.push('Add at least one content item.');d.entries.forEach((e,i)=>{if(!e.title.trim()||!e.content.trim())errors.push(`Item ${i+1}: complete both fields.`);});}return errors;}
export const cloneDocument=(d:BuilderDocument)=>({...structuredClone(d),id:uid(),title:`${d.title || 'Untitled document'} (copy)`,modified:new Date().toISOString()});
